"""add author to reviews table and make spice_rating nullable

Revision ID: 051646cdad54
Revises: cee2ef08a03b
Create Date: 2025-08-07 18:24:34.098836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051646cdad54'
down_revision = 'cee2ef08a03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=250), nullable=False))
        batch_op.alter_column('spice_rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_reviews', schema=None) as batch_op:
        batch_op.alter_column('spice_rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('author')

    # ### end Alembic commands ###
