"""add post_img to db

Revision ID: 23d9a464156a
Revises: a53908429d14
Create Date: 2025-08-13 19:04:09.355541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d9a464156a'
down_revision = 'a53908429d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_img', sa.String(length=2083), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('post_img')

    # ### end Alembic commands ###
